export const symptoms = [
  { value: "abdominal bloating", label: "abdominal bloating" },
  { value: "abnormal bleeding", label: "abnormal bleeding" },
  { value: "abnormal reflex", label: "abnormal reflex" },
  { value: "abnormally frequent", label: "abnormally frequent" },
  {
    value: "abnormally small head brain",
    label: "abnormally small head brain",
  },
  { value: "abscess", label: "abscess" },
  { value: "acne", label: "acne" },
  {
    value: "acquiring drinking alcohol taking lot time",
    label: "acquiring drinking alcohol taking lot time",
  },
  {
    value: "affected part turning white",
    label: "affected part turning white",
  },
  { value: "anemia", label: "anemia" },
  { value: "anxiety", label: "anxiety" },
  { value: "arm", label: "arm" },
  { value: "asthenopia", label: "asthenopia" },
  { value: "asymptomatic early stage", label: "asymptomatic early stage" },
  { value: "back", label: "back" },
  { value: "bad breath", label: "bad breath" },
  {
    value: "bad smelling vaginal discharge",
    label: "bad smelling vaginal discharge",
  },
  { value: "barking cough", label: "barking cough" },
  { value: "better sitting worse lying", label: "better sitting worse lying" },
  {
    value: "birth baby younger week gestational age",
    label: "birth baby younger week gestational age",
  },
  { value: "black area skin", label: "black area skin" },
  { value: "bleeding gum", label: "bleeding gum" },
  { value: "bleeding skin", label: "bleeding skin" },
  { value: "blindness", label: "blindness" },
  {
    value: "blister break open form small ulcer",
    label: "blister break open form small ulcer",
  },
  { value: "bloating", label: "bloating" },
  { value: "blood stool", label: "blood stool" },
  { value: "bloody diarrhea", label: "bloody diarrhea" },
  { value: "blue", label: "blue" },
  { value: "blurred vision", label: "blurred vision" },
  {
    value: "blurred vision center visual field",
    label: "blurred vision center visual field",
  },
  { value: "blurry vision", label: "blurry vision" },
  { value: "bone tendon loss", label: "bone tendon loss" },
  { value: "breathlessness", label: "breathlessness" },
  { value: "bruising", label: "bruising" },
  { value: "burning sensation", label: "burning sensation" },
  { value: "burning stabbing pain", label: "burning stabbing pain" },
  { value: "burning urination", label: "burning urination" },
  { value: "case asymptomatic", label: "case asymptomatic" },
  { value: "certain thought repeatedly", label: "certain thought repeatedly" },
  { value: "change bowel movement", label: "change bowel movement" },
  { value: "change breast shape", label: "change breast shape" },
  { value: "change hair", label: "change hair" },
  { value: "change reflex", label: "change reflex" },
  {
    value: "change skin color red black",
    label: "change skin color red black",
  },
  {
    value: "change sleeping eating pattern",
    label: "change sleeping eating pattern",
  },
  { value: "change taste", label: "change taste" },
  { value: "change voice", label: "change voice" },
  {
    value: "characteristic facial feature",
    label: "characteristic facial feature",
  },
  { value: "chest discomfort", label: "chest discomfort" },
  { value: "chest pain", label: "chest pain" },
  { value: "chest tightness", label: "chest tightness" },
  { value: "chill", label: "chill" },
  { value: "chronic cough", label: "chronic cough" },
  { value: "close object appear normal", label: "close object appear normal" },
  { value: "clumsiness", label: "clumsiness" },
  { value: "cm lump skin", label: "cm lump skin" },
  { value: "cold sweat", label: "cold sweat" },
  { value: "coma", label: "coma" },
  { value: "confused thinking", label: "confused thinking" },
  { value: "confusion", label: "confusion" },
  { value: "constipation", label: "constipation" },
  { value: "coolness", label: "coolness" },
  { value: "cough bloody mucus", label: "cough bloody mucus" },
  { value: "coughing", label: "coughing" },
  { value: "coughing mucus", label: "coughing mucus" },
  { value: "cramped jaw", label: "cramped jaw" },
  { value: "crusty eyelid", label: "crusty eyelid" },
  { value: "crusty red nodule", label: "crusty red nodule" },
  { value: "cry episode", label: "cry episode" },
  { value: "dark urine", label: "dark urine" },
  { value: "darker", label: "darker" },
  { value: "daytime sleepiness", label: "daytime sleepiness" },
  {
    value: "decreased ability concentrate",
    label: "decreased ability concentrate",
  },
  {
    value: "decreased ability feel pain",
    label: "decreased ability feel pain",
  },
  { value: "decreased ability hear", label: "decreased ability hear" },
  { value: "decreased ability see", label: "decreased ability see" },
  {
    value: "decreased ability think remember",
    label: "decreased ability think remember",
  },
  { value: "decreased appetite", label: "decreased appetite" },
  { value: "decreased motivation", label: "decreased motivation" },
  { value: "decreased range motion", label: "decreased range motion" },
  { value: "decreased taste", label: "decreased taste" },
  { value: "decreased vision", label: "decreased vision" },
  { value: "dehydration", label: "dehydration" },
  { value: "delayed physical growth", label: "delayed physical growth" },
  { value: "delusion", label: "delusion" },
  {
    value: "depends location runny nose",
    label: "depends location runny nose",
  },
  { value: "depends organ involved", label: "depends organ involved" },
  {
    value: "deposit cholesterol eye lid",
    label: "deposit cholesterol eye lid",
  },
  { value: "depressed mood", label: "depressed mood" },
  { value: "depression", label: "depression" },
  { value: "developmental disability", label: "developmental disability" },
  { value: "diarrhea constipation", label: "diarrhea constipation" },
  { value: "diarrhea mixed blood", label: "diarrhea mixed blood" },
  { value: "diarrhoea", label: "diarrhoea" },
  { value: "diarrhoea may bloody", label: "diarrhoea may bloody" },
  { value: "difficulty breathing", label: "difficulty breathing" },
  { value: "difficulty cutting", label: "difficulty cutting" },
  { value: "difficulty eating", label: "difficulty eating" },
  {
    value: "difficulty getting pregnant",
    label: "difficulty getting pregnant",
  },
  {
    value: "difficulty reading small print",
    label: "difficulty reading small print",
  },
  { value: "difficulty swallowing", label: "difficulty swallowing" },
  { value: "difficulty walking", label: "difficulty walking" },
  { value: "digestive issue", label: "digestive issue" },
  { value: "dimpling skin", label: "dimpling skin" },
  { value: "disorientation", label: "disorientation" },
  { value: "distance near blur", label: "distance near blur" },
  {
    value: "distant object appear blurry",
    label: "distant object appear blurry",
  },
  {
    value: "distorted blurred vision distance",
    label: "distorted blurred vision distance",
  },
  {
    value: "drinking large amount alcohol long period",
    label: "drinking large amount alcohol long period",
  },
  { value: "dry cough", label: "dry cough" },
  { value: "dry damp skin", label: "dry damp skin" },
  { value: "dry eye", label: "dry eye" },
  { value: "dry mouth", label: "dry mouth" },
  { value: "dryness", label: "dryness" },
  { value: "ear pain", label: "ear pain" },
  { value: "easy bleeding", label: "easy bleeding" },
  { value: "easy prolonged bleeding", label: "easy prolonged bleeding" },
  { value: "emotional problem", label: "emotional problem" },
  { value: "enlarged spleen", label: "enlarged spleen" },
  { value: "episode severe", label: "episode severe" },
  { value: "erythema", label: "erythema" },
  { value: "erythema marginatum", label: "erythema marginatum" },
  { value: "excess hair", label: "excess hair" },
  {
    value: "excessive amount uterine bleeding",
    label: "excessive amount uterine bleeding",
  },
  {
    value: "excessive daytime sleepiness",
    label: "excessive daytime sleepiness",
  },
  { value: "excessive salivation", label: "excessive salivation" },
  { value: "extreme sadness", label: "extreme sadness" },
  { value: "eye pain photophobia", label: "eye pain photophobia" },
  { value: "eye redness", label: "eye redness" },
  {
    value: "eye refractive power differs significantly",
    label: "eye refractive power differs significantly",
  },
  { value: "eye strain", label: "eye strain" },
  { value: "facial swelling", label: "facial swelling" },
  { value: "fast heart rate", label: "fast heart rate" },
  { value: "fear water", label: "fear water" },
  {
    value: "feel need check thing repeatedly",
    label: "feel need check thing repeatedly",
  },
  { value: "feeling cold", label: "feeling cold" },
  { value: "feeling faint", label: "feeling faint" },
  {
    value: "feeling faint upon standing",
    label: "feeling faint upon standing",
  },
  { value: "feeling tired", label: "feeling tired" },
  { value: "fever", label: "fever" },
  {
    value: "fever start low increase daily",
    label: "fever start low increase daily",
  },
  { value: "firm", label: "firm" },
  {
    value: "flat discolored spot bump may blister",
    label: "flat discolored spot bump may blister",
  },
  { value: "flatulence", label: "flatulence" },
  { value: "flu like illness", label: "flu like illness" },
  { value: "fluid nipple", label: "fluid nipple" },
  { value: "frequent urination", label: "frequent urination" },
  { value: "fullness", label: "fullness" },
  { value: "gum disease", label: "gum disease" },
  { value: "half ring finger", label: "half ring finger" },
  { value: "hallucination", label: "hallucination" },
  {
    value: "hallucination usually hearing voice",
    label: "hallucination usually hearing voice",
  },
  { value: "hard swelling skin", label: "hard swelling skin" },
  { value: "headache", label: "headache" },
  { value: "hearing loss", label: "hearing loss" },
  { value: "heartburn", label: "heartburn" },
  { value: "high blood pressure", label: "high blood pressure" },
  { value: "high body temperature", label: "high body temperature" },
  { value: "hoarse voice", label: "hoarse voice" },
  {
    value: "hold reading material farther away",
    label: "hold reading material farther away",
  },
  { value: "inability child", label: "inability child" },
  {
    value: "inability move facial muscle one side",
    label: "inability move facial muscle one side",
  },
  {
    value: "inability move feel one side body",
    label: "inability move feel one side body",
  },
  { value: "increased breath rate", label: "increased breath rate" },
  { value: "increased fat", label: "increased fat" },
  { value: "increased heart rate", label: "increased heart rate" },
  { value: "increased hunger", label: "increased hunger" },
  { value: "increased risk broken bone", label: "increased risk broken bone" },
  { value: "increased risk infection", label: "increased risk infection" },
  { value: "index", label: "index" },
  { value: "infertility", label: "infertility" },
  { value: "inflamed eye", label: "inflamed eye" },
  { value: "intellectual disability", label: "intellectual disability" },
  { value: "internal bleeding", label: "internal bleeding" },
  {
    value: "involuntary muscle movement",
    label: "involuntary muscle movement",
  },
  { value: "involuntary sleep episode", label: "involuntary sleep episode" },
  { value: "irregular", label: "irregular" },
  { value: "irregular menstrual period", label: "irregular menstrual period" },
  { value: "irritability", label: "irritability" },
  { value: "irritation", label: "irritation" },
  { value: "itchiness", label: "itchiness" },
  { value: "itchy", label: "itchy" },
  { value: "itchy blister", label: "itchy blister" },
  { value: "itchy bump", label: "itchy bump" },
  { value: "joint bone pain", label: "joint bone pain" },
  { value: "joint swelling", label: "joint swelling" },
  {
    value: "large amount watery diarrhea",
    label: "large amount watery diarrhea",
  },
  {
    value: "lastly cause liver dysfunction eventually liver failure",
    label: "lastly cause liver dysfunction eventually liver failure",
  },
  { value: "later stage", label: "later stage" },
  { value: "light sensitivity", label: "light sensitivity" },
  { value: "lightheadedness", label: "lightheadedness" },
  { value: "limited range motion ankle", label: "limited range motion ankle" },
  { value: "little pain", label: "little pain" },
  {
    value: "localized breast pain redness",
    label: "localized breast pain redness",
  },
  {
    value: "loose frequent bowel movement",
    label: "loose frequent bowel movement",
  },
  { value: "loose teeth", label: "loose teeth" },
  { value: "loss appetite", label: "loss appetite" },
  { value: "loss bladder bowel control", label: "loss bladder bowel control" },
  { value: "loss hair part head body", label: "loss hair part head body" },
  { value: "loss smell", label: "loss smell" },
  { value: "loss taste smell", label: "loss taste smell" },
  { value: "loss vision one side", label: "loss vision one side" },
  { value: "low energy", label: "low energy" },
  { value: "lower abdominal pain", label: "lower abdominal pain" },
  { value: "lump breast", label: "lump breast" },
  { value: "lump bump neck", label: "lump bump neck" },
  { value: "maculopapular rash", label: "maculopapular rash" },
  { value: "malaise", label: "malaise" },
  { value: "may symptom", label: "may symptom" },
  { value: "memory loss", label: "memory loss" },
  { value: "memory problem", label: "memory problem" },
  { value: "mental change", label: "mental change" },
  { value: "mid dilated pupil", label: "mid dilated pupil" },
  { value: "middle finger", label: "middle finger" },
  {
    value: "mild moderate intellectual disability",
    label: "mild moderate intellectual disability",
  },
  { value: "minimal", label: "minimal" },
  { value: "mood change", label: "mood change" },
  { value: "mood swing", label: "mood swing" },
  { value: "multiple painful joint", label: "multiple painful joint" },
  { value: "muscle ache", label: "muscle ache" },
  { value: "muscle cramp", label: "muscle cramp" },
  { value: "muscle joint pain", label: "muscle joint pain" },
  { value: "muscle pain", label: "muscle pain" },
  { value: "muscle spasm", label: "muscle spasm" },
  {
    value: "muscle weakness beginning foot hand",
    label: "muscle weakness beginning foot hand",
  },
  {
    value: "muscle weakness resulting inability move",
    label: "muscle weakness resulting inability move",
  },
  { value: "muscular pain", label: "muscular pain" },
  { value: "nausea", label: "nausea" },
  {
    value: "nausea vomiting weight loss dehydration occur",
    label: "nausea vomiting weight loss dehydration occur",
  },
  { value: "nearly undetectable spell", label: "nearly undetectable spell" },
  { value: "nearsightedness", label: "nearsightedness" },
  { value: "neck", label: "neck" },
  { value: "neck stiffness", label: "neck stiffness" },
  { value: "neurological impairment", label: "neurological impairment" },
  { value: "newly inverted nipple", label: "newly inverted nipple" },
  { value: "night blindness", label: "night blindness" },
  { value: "non itchy skin ulcer", label: "non itchy skin ulcer" },
  {
    value: "non painful cyst middle eyelid",
    label: "non painful cyst middle eyelid",
  },
  { value: "nonaligned eye", label: "nonaligned eye" },
  { value: "numbness", label: "numbness" },
  { value: "object different size eye", label: "object different size eye" },
  {
    value: "opening upper lip may extend nose palate",
    label: "opening upper lip may extend nose palate",
  },
  { value: "overlying redness", label: "overlying redness" },
  { value: "pain area", label: "pain area" },
  { value: "pain around ear", label: "pain around ear" },
  {
    value: "pain doesnt end shingle subsides",
    label: "pain doesnt end shingle subsides",
  },
  { value: "pain specific bone", label: "pain specific bone" },
  { value: "painful", label: "painful" },
  {
    value: "painful blister white worm crawl",
    label: "painful blister white worm crawl",
  },
  { value: "painful heavy period", label: "painful heavy period" },
  {
    value: "painful sore inside mouth white gray red border",
    label: "painful sore inside mouth white gray red border",
  },
  { value: "painless", label: "painless" },
  { value: "painless lump", label: "painless lump" },
  { value: "painless mass", label: "painless mass" },
  { value: "pale color", label: "pale color" },
  { value: "pale skin", label: "pale skin" },
  { value: "pallor", label: "pallor" },
  { value: "paralysis", label: "paralysis" },
  { value: "paranoia", label: "paranoia" },
  {
    value: "parotitis non specific symptom fever",
    label: "parotitis non specific symptom fever",
  },
  { value: "patch thick", label: "patch thick" },
  { value: "patch white skin", label: "patch white skin" },
  {
    value: "perform certain routine repeatedly",
    label: "perform certain routine repeatedly",
  },
  { value: "period vigorous shaking", label: "period vigorous shaking" },
  {
    value: "periumbilical right lower abdominal pain",
    label: "periumbilical right lower abdominal pain",
  },
  { value: "persistent dry cough", label: "persistent dry cough" },
  {
    value: "persistent rough white red patch mouth lasting longer week",
    label: "persistent rough white red patch mouth lasting longer week",
  },
  { value: "physical disability", label: "physical disability" },
  { value: "pimple like rash", label: "pimple like rash" },
  { value: "pin needle sensation", label: "pin needle sensation" },
  { value: "pinkish", label: "pinkish" },
  {
    value: "playing video game extremely long period time",
    label: "playing video game extremely long period time",
  },
  { value: "poor appetite", label: "poor appetite" },
  {
    value: "possibly reaching high f c headache",
    label: "possibly reaching high f c headache",
  },
  { value: "post nasal drip", label: "post nasal drip" },
  {
    value: "presence restricted interest repetitive behavior",
    label: "presence restricted interest repetitive behavior",
  },
  { value: "problem gambling", label: "problem gambling" },
  { value: "problem language", label: "problem language" },
  {
    value: "problem understanding speaking",
    label: "problem understanding speaking",
  },
  { value: "problem vision", label: "problem vision" },
  { value: "prolonged cough", label: "prolonged cough" },
  { value: "protein urine", label: "protein urine" },
  { value: "purple colored skin lesion", label: "purple colored skin lesion" },
  { value: "raised", label: "raised" },
  { value: "raised red blue lesion", label: "raised red blue lesion" },
  { value: "recurring episode wheezing", label: "recurring episode wheezing" },
  { value: "red eye", label: "red eye" },
  { value: "red purple darker skin", label: "red purple darker skin" },
  {
    value: "red scaly patch skin breast",
    label: "red scaly patch skin breast",
  },
  { value: "red skin", label: "red skin" },
  { value: "red spot white eye", label: "red spot white eye" },
  { value: "red without blister", label: "red without blister" },
  { value: "reddish eye", label: "reddish eye" },
  { value: "redness", label: "redness" },
  {
    value: "redness sweating cheek area salivating",
    label: "redness sweating cheek area salivating",
  },
  { value: "rigidity", label: "rigidity" },
  { value: "round", label: "round" },
  { value: "runny nose", label: "runny nose" },
  { value: "scaly patch skin", label: "scaly patch skin" },
  { value: "scratchiness", label: "scratchiness" },
  { value: "seizure", label: "seizure" },
  { value: "sensitivity smell", label: "sensitivity smell" },
  { value: "sensitivity sound", label: "sensitivity sound" },
  { value: "shakiness", label: "shakiness" },
  { value: "sharp chest pain", label: "sharp chest pain" },
  {
    value: "shock like pain one side face last second minute",
    label: "shock like pain one side face last second minute",
  },
  { value: "short stature", label: "short stature" },
  { value: "shortness breath", label: "shortness breath" },
  {
    value: "significant blood loss childbirth",
    label: "significant blood loss childbirth",
  },
  { value: "skin breakdown", label: "skin breakdown" },
  { value: "sleep problem", label: "sleep problem" },
  { value: "slowness movement", label: "slowness movement" },
  { value: "sluggishness", label: "sluggishness" },
  { value: "small", label: "small" },
  {
    value: "small blister surrounding swelling",
    label: "small blister surrounding swelling",
  },
  { value: "snoring", label: "snoring" },
  { value: "social withdrawal", label: "social withdrawal" },
  { value: "sometimes none", label: "sometimes none" },
  { value: "sore arm leg", label: "sore arm leg" },
  { value: "sore throat", label: "sore throat" },
  { value: "stiff neck", label: "stiff neck" },
  { value: "stiffness", label: "stiffness" },
  { value: "stomach pain", label: "stomach pain" },
  { value: "sudden", label: "sudden" },
  {
    value: "sudden loss muscle strength",
    label: "sudden loss muscle strength",
  },
  { value: "sweating", label: "sweating" },
  { value: "swell pain near tumor", label: "swell pain near tumor" },
  { value: "swelling skin", label: "swelling skin" },
  { value: "swollen", label: "swollen" },
  { value: "swollen hand foot", label: "swollen hand foot" },
  { value: "swollen lymph node", label: "swollen lymph node" },
  {
    value: "swollen lymph node severe case",
    label: "swollen lymph node severe case",
  },
  {
    value: "swollen stomach enlarged liver spleen",
    label: "swollen stomach enlarged liver spleen",
  },
  { value: "taste acid", label: "taste acid" },
  { value: "tearing", label: "tearing" },
  {
    value: "temporary fleeting vision one eye",
    label: "temporary fleeting vision one eye",
  },
  { value: "tender breast", label: "tender breast" },
  { value: "tenderness", label: "tenderness" },
  { value: "testicular pain", label: "testicular pain" },
  { value: "thick skin crack", label: "thick skin crack" },
  {
    value: "tingling burning sensation prior sore development",
    label: "tingling burning sensation prior sore development",
  },
  { value: "tingling hand foot", label: "tingling hand foot" },
  { value: "tingling thumb", label: "tingling thumb" },
  { value: "tiredness", label: "tiredness" },
  { value: "tooth loss", label: "tooth loss" },
  { value: "tremor", label: "tremor" },
  {
    value: "triangular tissue growth cornea",
    label: "triangular tissue growth cornea",
  },
  { value: "trouble breathing nose", label: "trouble breathing nose" },
  { value: "trouble opening mouth", label: "trouble opening mouth" },
  { value: "trouble sleeping", label: "trouble sleeping" },
  { value: "trouble social interaction", label: "trouble social interaction" },
  { value: "trouble swallowing", label: "trouble swallowing" },
  { value: "ulcer around genitals", label: "ulcer around genitals" },
  { value: "ulceration", label: "ulceration" },
  { value: "unexplained weight loss", label: "unexplained weight loss" },
  {
    value: "unpleasant smell present breath",
    label: "unpleasant smell present breath",
  },
  { value: "usage resulting problem", label: "usage resulting problem" },
  { value: "usually ascending", label: "usually ascending" },
  {
    value: "vaginal bleeding without pain",
    label: "vaginal bleeding without pain",
  },
  { value: "vaginal discharge", label: "vaginal discharge" },
  { value: "variable", label: "variable" },
  {
    value: "vary depending part brain involved",
    label: "vary depending part brain involved",
  },
  { value: "velvety skin", label: "velvety skin" },
  {
    value: "verbal nonverbal communication",
    label: "verbal nonverbal communication",
  },
  { value: "vision loss", label: "vision loss" },
  { value: "vomiting", label: "vomiting" },
  { value: "vomiting blood", label: "vomiting blood" },
  {
    value: "vomiting diarrhea muscle ache rash",
    label: "vomiting diarrhea muscle ache rash",
  },
  { value: "weakness", label: "weakness" },
  { value: "weakness fatigue", label: "weakness fatigue" },
  { value: "webbed neck", label: "webbed neck" },
  { value: "wheezing", label: "wheezing" },
  {
    value: "withdrawal occurring stopping",
    label: "withdrawal occurring stopping",
  },
  { value: "worrying", label: "worrying" },
  { value: "yellow skin", label: "yellow skin" },
  {
    value: "yellowish coloration skin white eye",
    label: "yellowish coloration skin white eye",
  },
  { value: "yellowish skin", label: "yellowish skin" },
];
